version: '1'

services:
  db:
    image: 'postgres:11.1'
    container_name: 'my_cloud_app_db'
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
  cloud_app_koryakin:
    image: 'my_cloud_app:latest'
    ports:
      - '8080:8080'
    depends_on:
      - 'db'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update